interface ImportMetaEnv {
    VITE_APP_ACCESS_TOKEN_MAPBOX: string
    VITE_APP_ACCESS_STYLE_MAP_MAPBOX: string
    VITE_APP_API_VERSION: string
    VITE_APP_API_BASE_URL: string
    VITE_APP_API_LOCAL_BASE_URL: string
    VITE_APP_API_JS_BASE_URL: string
    VITE_APP_API_PYTHON_BASE_URL: string
    VITE_APP_API_RESOURCE_APARTMENTS: string
    VITE_APP_API_RESOURCE_GEO: string
    VITE_APP_API_RESOURCE_SEARCH_FAKE: string
    VITE_APP_API_RESOURCE_SEARCH_REAL: string
}