interface ImportMetaEnv {
    VITE_APP_ACCESS_TOKEN_MAPBOX: string
    VITE_APP_ACCESS_STYLE_MAP_MAPBOX: string
    VITE_APP_API_VERSION: string
    VITE_APP_API_BASE_URL: string
    VITE_APP_API_LOCAL_BASE_URL: string
    VITE_APP_API_JS_BASE_URL: string
    VITE_APP_API_PYTHON_BASE_URL: string
    VITE_APP_API_RESOURCE_APARTMENTS: string
    VITE_APP_API_RESOURCE_ADDRESSES: string
    VITE_APP_API_RESOURCE_COUNTRIES: string
    VITE_APP_API_RESOURCE_STATES: string
    VITE_APP_API_RESOURCE_CITY: string
    VITE_APP_API_RESOURCE_NEIGHBORHOOD: string
    VITE_APP_API_RESOURCE_CITY_HALL: string
    VITE_APP_API_RESOURCE_FEATURES: string
    VITE_APP_API_RESOURCE_GEO: string
    VITE_APP_API_RESOURCE_SEARCH_FAKE: string
    VITE_APP_API_RESOURCE_SEARCH_REAL: string
}